# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - localhost:9090

  - job_name: 'node'
    static_configs:
      - targets: ['docker01:9100','docker02:9100','docker03:9100']

      
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['docker01:9101','docker02:9101','docker03:9101']

